### PR TITLE
Add batch processing to improve performance

### PR DESCRIPTION
**Pull request by dignifiedquire**
In reference to my comment here, https://github.com/ipfs/notes/issues/2#issuecomment-156721856 I tried to add some parallelized batch processing which has improved resource usage and performance drastically for me.

cc @bengl

### CODE REVIEW

**Comment by davglass** [comment]
@Dignifiedquire Looks like you forgot to add the `async` module to the `package.json` so the build failed. Can you add that and make sure that all of the current tests pass? Maybe even adding in more? Thanks! :beers:

**Comment by dignifiedquire** [comment]
@davglass uups sorry about that :( should be all good now. The current tests are passing now, not sure how to add a good test for this though. If you have any suggestions I'm happy to write one.

**Comment by daviddias** [comment]
Been using this PR and it is golden! :D

**Comment by davglass** [comment]
I'll let @bengl handle this since he's been running this and `registry-static` for me for a while. It's his call :smile:

**Pull request merged**
